'use strict';
const $ = id => document.getElementById(id);
const key = 'hereai-workspace-v1';
const seed = {people:[{id:'HAI-001',name:'Alex Morgan',className:'Computer Science · A',details:'Year 2'},{id:'HAI-002',name:'Sam Rivera',className:'Computer Science · A',details:'Year 2'},{id:'HAI-003',name:'Jordan Lee',className:'Design · B',details:'Year 1'}],records:[],audit:[]};
let state;
try {state=JSON.parse(localStorage.getItem(key)); if(!Array.isArray(state?.people)||!Array.isArray(state?.records)||!Array.isArray(state?.audit))state=null;}catch{state=null;}
state ||= structuredClone(seed);
let lastCheckin=null;
const day = (date=new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize = value => value.trim().toUpperCase();
const clock = iso => new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true;}catch{alert('Browser storage is unavailable. Changes remain in memory only; export your attendance before closing.');return false;}}
function table(headings,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headings.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:'<div class="empty">Nothing here yet. Your next check-in starts the story.</div>';}
function recordsFiltered(){return state.records.filter(r=>(!$('class-filter').value||r.className===$('class-filter').value)&&(!$('date-filter').value||r.day===$('date-filter').value)).sort((a,b)=>b.timestamp.localeCompare(a.timestamp));}
function recordRow(r){return `<tr><td>${esc(r.name)}<small>${esc(r.personId)}</small></td><td>${esc(r.className)}</td><td>${esc(r.day)}</td><td>${esc(clock(r.timestamp))}</td><td><span class="badge">Present</span></td></tr>`;}
function render(){
 const today=state.records.filter(r=>r.day===day());
 $('people-count').textContent=state.people.length;$('present-count').textContent=today.length;$('rate').textContent=`${state.people.length?Math.round(today.length/state.people.length*100):0}%`;
 const classes=[...new Set(state.people.map(p=>p.className))].sort();$('class-count').textContent=classes.length;
 const filter=$('class-filter').value;$('class-filter').innerHTML='<option value="">All classes</option>'+classes.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('class-filter').value=classes.includes(filter)?filter:'';
 const selected=$('demo-person').value;$('demo-person').innerHTML=state.people.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.id)}</option>`).join('');if(state.people.some(p=>p.id===selected))$('demo-person').value=selected;
 $('recent').innerHTML=table(['PERSON','CLASS','DATE','CHECK-IN','STATUS'],today.slice().reverse().slice(0,5).map(recordRow));renderPeople();renderRecords();
 $('today-label').textContent=new Date().toLocaleDateString([],{day:'numeric',month:'long',year:'numeric'});
}
function renderPeople(){const query=$('people-search').value.toLowerCase();$('people-table').innerHTML=table(['PERSON','STUDENT ID','CLASS','DETAILS','QR PASS'],state.people.filter(p=>`${p.name} ${p.id} ${p.className}`.toLowerCase().includes(query)).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.id)}</td><td>${esc(p.className)}</td><td>${esc(p.details)||'—'}</td><td><button class="text-button" data-qr="${esc(p.id)}">Show QR ↗</button></td></tr>`));}
function renderRecords(){$('records-table').innerHTML=table(['PERSON','CLASS','DATE','CHECK-IN','STATUS'],recordsFiltered().map(recordRow));}
function navigate(view){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('breadcrumb').textContent=document.querySelector(`nav [data-view="${view}"] span`).textContent;}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.view)));
document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close()));
function openEnroll(){$('enroll-form').reset();$('enroll-error').textContent='';$('enroll-dialog').showModal();}
$('add-person').onclick=openEnroll;$('quick-add').onclick=openEnroll;
$('enroll-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);const person={name:data.get('name').trim(),id:normalize(data.get('id')),className:data.get('className').trim(),details:data.get('details').trim()};if(!person.name||!person.id||!person.className){$('enroll-error').textContent='Enter a name, ID and class.';return;}if(state.people.some(p=>p.id===person.id)){$('enroll-error').textContent='This student ID is already enrolled. Use a unique ID.';return;}state.people.push(person);save();render();$('enroll-dialog').close();navigate('people');showQR(person.id);});
function mark(person){const existing=state.records.find(r=>r.personId===person.id&&r.day===day());if(existing)return {record:existing,created:false};const record={recordId:crypto.randomUUID(),personId:person.id,name:person.name,className:person.className,day:day(),timestamp:new Date().toISOString(),method:'student-id'};state.records.push(record);save();render();return {record,created:true};}
function confirmation(person,result,simulated=false){lastCheckin={...result,simulated};$('success-kind').textContent=simulated?'SIMULATED RECOGNITION · NO ATTENDANCE SAVED':result.created?'CHECK-IN COMPLETE':'ALREADY CHECKED IN TODAY';$('success-title').textContent=simulated?`Demo recognized ${person.name}`:`Attendance marked for ${person.name}!`;$('success-details').textContent=[person.id,person.className,person.details].filter(Boolean).join(' · ');$('success-time').textContent=simulated?'Selected demo identity. No face recognition was performed.':`Present · ${clock(result.record.timestamp)} · ${result.record.day}`;$('correction-form').hidden=true;$('not-you').hidden=false;$('correction-error').textContent='';$('correct-id').value='';$('success-dialog').showModal();}
$('checkin-form').addEventListener('submit',event=>{event.preventDefault();const person=state.people.find(p=>p.id===normalize($('student-id').value));if(!person){$('checkin-message').textContent='ID not found. Ask the administrator to enroll you first.';return;}$('checkin-message').textContent='';confirmation(person,mark(person));$('student-id').value='';});
$('simulate').onclick=()=>{const person=state.people.find(p=>p.id===$('demo-person').value);if(person)confirmation(person,{record:null,created:false},true);};
$('not-you').onclick=()=>{$('correction-form').hidden=false;$('not-you').hidden=true;$('correction-note').textContent=lastCheckin.simulated?'Entering your ID will make a real attendance entry in this local prototype.':'This will replace the check-in just created. Existing earlier check-ins stay recorded.';$('correct-id').focus();};
$('correction-form').addEventListener('submit',event=>{event.preventDefault();const person=state.people.find(p=>p.id===normalize($('correct-id').value));if(!person){$('correction-error').textContent='ID not found. Please ask an administrator to enroll you.';return;}if(!lastCheckin.simulated&&lastCheckin.record.personId===person.id){$('correction-error').textContent='This is the same student ID. Enter the correct person’s ID.';return;}const previous=lastCheckin.record;const removed=!!(lastCheckin.created&&!lastCheckin.simulated);if(removed)state.records=state.records.filter(r=>r.recordId!==previous.recordId);state.audit.push({timestamp:new Date().toISOString(),action:'identity-correction',previousPersonId:previous?.personId??null,correctedPersonId:person.id,removedRecordId:removed?previous.recordId:null});const result=mark(person);save();render();$('success-dialog').close();confirmation(person,result);});
$('people-search').addEventListener('input',renderPeople);$('class-filter').addEventListener('change',renderRecords);$('date-filter').addEventListener('change',renderRecords);$('clear-filters').onclick=()=>{$('class-filter').value='';$('date-filter').value='';renderRecords();};
function csvCell(value){let text=String(value??'');if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
$('export').onclick=()=>{const rows=recordsFiltered();const content=[['Name','Student ID','Class','Date','Timestamp (UTC)','Status'],...rows.map(r=>[r.name,r.personId,r.className,r.day,r.timestamp,'Present'])].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/csv;charset=utf-8;'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`hereai-attendance-${day()}.csv`;anchor.click();URL.revokeObjectURL(url);};
render();
